#------------------------------------------------------------
# Copyright (c) 2019 Thomas Kais
#
# This file is subject to the terms and conditions defined in
# file 'COPYING', which is part of this source code package.
#------------------------------------------------------------

# blacklist
branches:
  except:
    - gh-pages

matrix:
  include:
    - name: "macOS"
      os: osx
      compiler: clang
      language: cpp
      before_install:
        - brew update
      install:
        #install latest Qt https://formulae.brew.sh/formula/qt and creates symlinks to installation
        - brew install qt
        - brew link --force qt
      before_script:
        - qmake --version
      script:
        - qmake -recursive
        - make -j2
      before_deploy:
        - macdeployqt FotoBox.app -verbose=2
        - cp ./other/README.pdf ./README.pdf
        - zip --verbose --symlinks --recurse-paths -9 FotoBox_macOS.zip FotoBox.app/ README.pdf

    - name: "Raspbian Stretch"
      os: linux
      dist: xenial
      language: ruby
      services:
        - docker
      before_install:
        #enable an execution of different multi-architecture containers by QEMU
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      install:
        #build FotoBox container
        - docker build --tag buildfotobox --file other/DockerfileStretch .
      script:
        #execute 'CMD' command (Dockerfile) to build
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

    - name: "Raspbian Buster"
      os: linux
      dist: xenial
      language: ruby
      services:
        - docker
      before_install:
        #enable an execution of different multi-architecture containers by QEMU
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
      install:
        #build FotoBox container
        - docker build --tag buildfotobox --file other/DockerfileBuster .
      script:
        #execute 'CMD' command (Dockerfile) to build
        - docker run --volume $TRAVIS_BUILD_DIR:/artifact buildfotobox

    - name: "Ubuntu Xenial CMake gcc"
      os: linux
      dist: xenial
      language: cpp
      compiler: gcc
      sudo: false
      addons:
        apt:
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
      before_script:
        - cmake --version
        - gcc --version
        - qmake --version
      script:
        - cmake CMakeLists.txt -G "Unix Makefiles"
        - make -j2
      before_deploy:
        - tar -cvzf ./FotoBox_Ubuntu_Xenial.tar.gz -C . FotoBox -C ./other/ README.pdf install_dependencies.sh

    - name: "Ubuntu Xenial CMake Debug clang diagnostic 8"
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            # https://apt.llvm.org
            - llvm-toolchain-xenial-8
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
            - clang-8
      env:
        - CC=clang-8
        - CXX=clang++-8
      before_script:
        - cmake --version
        - clang++-8 --version
      script:
        # QtCreator -> Analyze -> clang -> Rule: "Clang ... almost everything" rules and added '-Wno-padded'
        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-Wno-padded -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-unused-macros -Wno-newline-eof -Wno-exit-time-destructors -Wno-global-constructors -Wno-gnu-zero-variadic-macro-arguments -Wno-documentation -Wno-shadow -Wno-switch-enum -Wno-missing-prototypes -Wno-used-but-marked-unused"
        - make 2>&1 | tee output.txt
        - |
          if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
            echo -e "\033[1;31m\xE2\x9C\x93 clang failed!\033[0m";
            exit 1;
          else
            echo -e "\033[1;32m\xE2\x9C\x93 clang passed!\033[0m";
          fi

    - name: "Ubuntu Xenial CMake Debug clang tidy 8"
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            # https://apt.llvm.org
            - llvm-toolchain-xenial-8
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
            - llvm-8
            - clang-8
            - clang-tidy-8
      env:
        - CC=clang-8
        - CXX=clang++-8
        - CLANG_TIDY=clang-tidy-8
      before_script:
        - cmake --version
        - clang++-8 --version
        - clang-tidy-8 --version
      script:
        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Wno-everything" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CLANG_TIDY=ON
        - make -j2
        - make tidy 2>&1 | tee output.txt
        - |
          if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
            echo -e "\033[1;31m\xE2\x9C\x93 clang tidy failed!\033[0m";
            exit 1;
          else
            echo -e "\033[1;32m\xE2\x9C\x93 clang tidy passed!\033[0m";
          fi

    - name: "Ubuntu Xenial CMake Debug clang clazy 1.6"
      os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          update: true
          packages:
            - qt5-default
            - qttools5-dev-tools
            - libfuse2
      before_script:
        - wget -O clazy.AppImage https://downloads.kdab.com/clazy/1.6/Clazy-x86_64-1.6.AppImage
        - chmod +x clazy.AppImage
        - ./clazy.AppImage --version
        - ./clazy.AppImage --standalone -version
      script:
        - cmake CMakeLists.txt -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Wno-everything" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_CLANG_CLAZY=ON
        - make -j2
        - make clazy 2>&1 | tee output.txt
        - |
          if [[ -n $(grep -v "_autogen" output.txt | grep "warning: ") ]] || [[ -n $(grep -v "_autogen" output.txt | grep "error: ") ]]; then
            echo -e "\033[1;31m\xE2\x9C\x93 clang clazy failed!\033[0m";
            exit 1;
          else
            echo -e "\033[1;32m\xE2\x9C\x93 clang clazy passed!\033[0m";
          fi

    - name: "macOS Doxygen"
      os: osx
      osx_image: xcode11.3
      before_install:
        - brew update
      install:
        - brew install doxygen graphviz
      before_script:
        - doxygen --version
      script:
        - doxygen other/Doxyfile
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: html
        github_token: $GH_REPO_TOKEN
        keep-history: false
        on:
          branch: develop

notifications:
  slack: foto-box:QXDcNQc86kOdnsSHinv0sqd6

deploy:
  provider: releases
  api_key: $GH_REPO_TOKEN
  file:
    - FotoBox_macOS.zip
    - FotoBox_RasPi_Stretch.tar.gz
    - FotoBox_RasPi_Buster.tar.gz
    - FotoBox_Ubuntu_Xenial.tar.gz
  skip_cleanup: true
  on:
    tags: true
